import { GraphQLSchema, printSchema } from "graphql";
import { printSchema as printFederatedSchema } from "@apollo/federation";
import { Options as PrintSchemaOptions } from "graphql/utilities/schemaPrinter";

import { outputFile, outputFileSync } from "../helpers/filesystem";
import { getMetadataStorage } from "../metadata/getMetadataStorage";

export const defaultPrintSchemaOptions: PrintSchemaOptions = { commentDescriptions: false };

const generatedSchemaWarning = /* graphql */ `\
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

`;

function isFederated(): boolean {
  const metadata = getMetadataStorage();

  return metadata.federation && metadata.federation.useApolloFederation === true;
}

export function emitSchemaDefinitionFileSync(
  schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent =
    generatedSchemaWarning +
    (isFederated() ? printFederatedSchema(schema) : printSchema(schema, options));
  outputFileSync(schemaFilePath, schemaFileContent);
}

export async function emitSchemaDefinitionFile(
  schemaFilePath: string,
  schema: GraphQLSchema,
  options: PrintSchemaOptions = defaultPrintSchemaOptions,
) {
  const schemaFileContent =
    generatedSchemaWarning +
    (isFederated() ? printFederatedSchema(schema) : printSchema(schema, options));
  await outputFile(schemaFilePath, schemaFileContent);
}
